spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/eventlab # docker mysql 주소 사용
    username: root
    password: root

    ## hikariCP Connection Timeout 해결
    hikari:
      maximum-pool-size: 50    # 동시 커넥션 허용 수를 늘려서
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true # ????? ??
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ?? ?
        use_sql_comments: true #
    hibernate:
      ddl-auto: update

#  h2:
#    console:
#      enabled: true
#      path: /h2-console



  data:
    redis:
      # host: localhost
      host: redis # docker-compose 내부 주소 이름
      port: 6379

logging:
  level:
    org.springframework.transaction.interceptor: TRACE